MAX_KEY_CONCEPTS_PER_FILE = 4
MAX_KEY_CONCEPTS_TOTAL = 6
MAX_KEY_PROCESSES_PER_PLAYBOOK = 5

# GPT 5.1 supports 'none', 'low', 'medium', and 'high'
GLOBAL_CODEX_REASONING_EFFORT = "none" 
DIGEST_CODEX_REASONING_EFFORT = "low"
TRIAGE_CODEX_REASONING_EFFORT = "none"